# This is a basic workflow to help you get started with Actions

name: AzureMLTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  valiate_azureml:
    runs-on: ubuntu-latest
    
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_CREDS}}
      - name: setup
        run: bash setup.sh
        working-directory: setup
        continue-on-error: true
      - name: list job
        run: az ml job list
        
      
      
      
